// Code generated by MockGen. DO NOT EDIT.
// Source: order_grpc.pb.go

// Package mock_order is a generated GoMock package.
package mock_order

import (
	context "context"
	reflect "reflect"

	orders "github.com/go-park-mail-ru/2021_2_Good_Vibes/internal/app/tools/proto/order"
	gomock "github.com/golang/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockOrderServiceClient is a mock of OrderServiceClient interface.
type MockOrderServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceClientMockRecorder
}

// MockOrderServiceClientMockRecorder is the mock recorder for MockOrderServiceClient.
type MockOrderServiceClientMockRecorder struct {
	mock *MockOrderServiceClient
}

// NewMockOrderServiceClient creates a new mock instance.
func NewMockOrderServiceClient(ctrl *gomock.Controller) *MockOrderServiceClient {
	mock := &MockOrderServiceClient{ctrl: ctrl}
	mock.recorder = &MockOrderServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceClient) EXPECT() *MockOrderServiceClientMockRecorder {
	return m.recorder
}

// GetAllOrders mocks base method.
func (m *MockOrderServiceClient) GetAllOrders(ctx context.Context, in *orders.UserIdOrder, opts ...grpc.CallOption) (*orders.ArrayOrders, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllOrders", varargs...)
	ret0, _ := ret[0].(*orders.ArrayOrders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockOrderServiceClientMockRecorder) GetAllOrders(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockOrderServiceClient)(nil).GetAllOrders), varargs...)
}

// PutOrder mocks base method.
func (m *MockOrderServiceClient) PutOrder(ctx context.Context, in *orders.Order, opts ...grpc.CallOption) (*orders.OrderCost, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutOrder", varargs...)
	ret0, _ := ret[0].(*orders.OrderCost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutOrder indicates an expected call of PutOrder.
func (mr *MockOrderServiceClientMockRecorder) PutOrder(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutOrder", reflect.TypeOf((*MockOrderServiceClient)(nil).PutOrder), varargs...)
}

// MockOrderServiceServer is a mock of OrderServiceServer interface.
type MockOrderServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockOrderServiceServerMockRecorder
}

// MockOrderServiceServerMockRecorder is the mock recorder for MockOrderServiceServer.
type MockOrderServiceServerMockRecorder struct {
	mock *MockOrderServiceServer
}

// NewMockOrderServiceServer creates a new mock instance.
func NewMockOrderServiceServer(ctrl *gomock.Controller) *MockOrderServiceServer {
	mock := &MockOrderServiceServer{ctrl: ctrl}
	mock.recorder = &MockOrderServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderServiceServer) EXPECT() *MockOrderServiceServerMockRecorder {
	return m.recorder
}

// GetAllOrders mocks base method.
func (m *MockOrderServiceServer) GetAllOrders(arg0 context.Context, arg1 *orders.UserIdOrder) (*orders.ArrayOrders, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllOrders", arg0, arg1)
	ret0, _ := ret[0].(*orders.ArrayOrders)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllOrders indicates an expected call of GetAllOrders.
func (mr *MockOrderServiceServerMockRecorder) GetAllOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllOrders", reflect.TypeOf((*MockOrderServiceServer)(nil).GetAllOrders), arg0, arg1)
}

// PutOrder mocks base method.
func (m *MockOrderServiceServer) PutOrder(arg0 context.Context, arg1 *orders.Order) (*orders.OrderCost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutOrder", arg0, arg1)
	ret0, _ := ret[0].(*orders.OrderCost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutOrder indicates an expected call of PutOrder.
func (mr *MockOrderServiceServerMockRecorder) PutOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutOrder", reflect.TypeOf((*MockOrderServiceServer)(nil).PutOrder), arg0, arg1)
}

// mustEmbedUnimplementedOrderServiceServer mocks base method.
func (m *MockOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrderServiceServer")
}

// mustEmbedUnimplementedOrderServiceServer indicates an expected call of mustEmbedUnimplementedOrderServiceServer.
func (mr *MockOrderServiceServerMockRecorder) mustEmbedUnimplementedOrderServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrderServiceServer", reflect.TypeOf((*MockOrderServiceServer)(nil).mustEmbedUnimplementedOrderServiceServer))
}

// MockUnsafeOrderServiceServer is a mock of UnsafeOrderServiceServer interface.
type MockUnsafeOrderServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeOrderServiceServerMockRecorder
}

// MockUnsafeOrderServiceServerMockRecorder is the mock recorder for MockUnsafeOrderServiceServer.
type MockUnsafeOrderServiceServerMockRecorder struct {
	mock *MockUnsafeOrderServiceServer
}

// NewMockUnsafeOrderServiceServer creates a new mock instance.
func NewMockUnsafeOrderServiceServer(ctrl *gomock.Controller) *MockUnsafeOrderServiceServer {
	mock := &MockUnsafeOrderServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeOrderServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeOrderServiceServer) EXPECT() *MockUnsafeOrderServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedOrderServiceServer mocks base method.
func (m *MockUnsafeOrderServiceServer) mustEmbedUnimplementedOrderServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedOrderServiceServer")
}

// mustEmbedUnimplementedOrderServiceServer indicates an expected call of mustEmbedUnimplementedOrderServiceServer.
func (mr *MockUnsafeOrderServiceServerMockRecorder) mustEmbedUnimplementedOrderServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedOrderServiceServer", reflect.TypeOf((*MockUnsafeOrderServiceServer)(nil).mustEmbedUnimplementedOrderServiceServer))
}
