// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2021_2_Good_Vibes/internal/app/orders (interfaces: Repository)

// Package mock_order is a generated GoMock package.
package mock_order

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_2_Good_Vibes/internal/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// PutOrder mocks base method.
func (m *MockRepository) PutOrder(arg0 models.Order) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutOrder", arg0)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutOrder indicates an expected call of PutOrder.
func (mr *MockRepositoryMockRecorder) PutOrder(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutOrder", reflect.TypeOf((*MockRepository)(nil).PutOrder), arg0)
}

// SelectPrices mocks base method.
func (m *MockRepository) SelectPrices(arg0 []models.OrderProducts) ([]models.ProductPrice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectPrices", arg0)
	ret0, _ := ret[0].([]models.ProductPrice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectPrices indicates an expected call of SelectPrices.
func (mr *MockRepositoryMockRecorder) SelectPrices(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectPrices", reflect.TypeOf((*MockRepository)(nil).SelectPrices), arg0)
}
