// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/go-park-mail-ru/2021_2_Good_Vibes/internal/app/category (interfaces: Repository)

// Package mock_category is a generated GoMock package.
package mock_category

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_2_Good_Vibes/internal/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCategory mocks base method.
func (m *MockRepository) CreateCategory(arg0, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCategory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateCategory indicates an expected call of CreateCategory.
func (mr *MockRepositoryMockRecorder) CreateCategory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCategory", reflect.TypeOf((*MockRepository)(nil).CreateCategory), arg0, arg1)
}

// SelectAllCategories mocks base method.
func (m *MockRepository) SelectAllCategories() ([]models.NestingCategory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SelectAllCategories")
	ret0, _ := ret[0].([]models.NestingCategory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SelectAllCategories indicates an expected call of SelectAllCategories.
func (mr *MockRepositoryMockRecorder) SelectAllCategories() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SelectAllCategories", reflect.TypeOf((*MockRepository)(nil).SelectAllCategories))
}
