// Code generated by MockGen. DO NOT EDIT.
// Source: basket_grpc.pb.go

// Package mock_basket is a generated GoMock package.
package mock_basket

import (
	context "context"
	reflect "reflect"

	basket "github.com/go-park-mail-ru/2021_2_Good_Vibes/internal/app/tools/proto/basket"
	gomock "github.com/golang/mock/gomock"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
)

// MockBasketServiceClient is a mock of BasketServiceClient interface.
type MockBasketServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockBasketServiceClientMockRecorder
}

// MockBasketServiceClientMockRecorder is the mock recorder for MockBasketServiceClient.
type MockBasketServiceClientMockRecorder struct {
	mock *MockBasketServiceClient
}

// NewMockBasketServiceClient creates a new mock instance.
func NewMockBasketServiceClient(ctrl *gomock.Controller) *MockBasketServiceClient {
	mock := &MockBasketServiceClient{ctrl: ctrl}
	mock.recorder = &MockBasketServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketServiceClient) EXPECT() *MockBasketServiceClientMockRecorder {
	return m.recorder
}

// DeleteProduct mocks base method.
func (m *MockBasketServiceClient) DeleteProduct(ctx context.Context, in *basket.BasketProduct, opts ...grpc.CallOption) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DeleteProduct", varargs...)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockBasketServiceClientMockRecorder) DeleteProduct(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockBasketServiceClient)(nil).DeleteProduct), varargs...)
}

// DropBasket mocks base method.
func (m *MockBasketServiceClient) DropBasket(ctx context.Context, in *basket.UserID, opts ...grpc.CallOption) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DropBasket", varargs...)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DropBasket indicates an expected call of DropBasket.
func (mr *MockBasketServiceClientMockRecorder) DropBasket(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropBasket", reflect.TypeOf((*MockBasketServiceClient)(nil).DropBasket), varargs...)
}

// GetBasket mocks base method.
func (m *MockBasketServiceClient) GetBasket(ctx context.Context, in *basket.UserID, opts ...grpc.CallOption) (*basket.ProductArray, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetBasket", varargs...)
	ret0, _ := ret[0].(*basket.ProductArray)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasket indicates an expected call of GetBasket.
func (mr *MockBasketServiceClientMockRecorder) GetBasket(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasket", reflect.TypeOf((*MockBasketServiceClient)(nil).GetBasket), varargs...)
}

// PutInBasket mocks base method.
func (m *MockBasketServiceClient) PutInBasket(ctx context.Context, in *basket.BasketProduct, opts ...grpc.CallOption) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	varargs := []interface{}{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "PutInBasket", varargs...)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutInBasket indicates an expected call of PutInBasket.
func (mr *MockBasketServiceClientMockRecorder) PutInBasket(ctx, in interface{}, opts ...interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]interface{}{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutInBasket", reflect.TypeOf((*MockBasketServiceClient)(nil).PutInBasket), varargs...)
}

// MockBasketServiceServer is a mock of BasketServiceServer interface.
type MockBasketServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockBasketServiceServerMockRecorder
}

// MockBasketServiceServerMockRecorder is the mock recorder for MockBasketServiceServer.
type MockBasketServiceServerMockRecorder struct {
	mock *MockBasketServiceServer
}

// NewMockBasketServiceServer creates a new mock instance.
func NewMockBasketServiceServer(ctrl *gomock.Controller) *MockBasketServiceServer {
	mock := &MockBasketServiceServer{ctrl: ctrl}
	mock.recorder = &MockBasketServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBasketServiceServer) EXPECT() *MockBasketServiceServerMockRecorder {
	return m.recorder
}

// DeleteProduct mocks base method.
func (m *MockBasketServiceServer) DeleteProduct(arg0 context.Context, arg1 *basket.BasketProduct) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0, arg1)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockBasketServiceServerMockRecorder) DeleteProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockBasketServiceServer)(nil).DeleteProduct), arg0, arg1)
}

// DropBasket mocks base method.
func (m *MockBasketServiceServer) DropBasket(arg0 context.Context, arg1 *basket.UserID) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropBasket", arg0, arg1)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DropBasket indicates an expected call of DropBasket.
func (mr *MockBasketServiceServerMockRecorder) DropBasket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropBasket", reflect.TypeOf((*MockBasketServiceServer)(nil).DropBasket), arg0, arg1)
}

// GetBasket mocks base method.
func (m *MockBasketServiceServer) GetBasket(arg0 context.Context, arg1 *basket.UserID) (*basket.ProductArray, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasket", arg0, arg1)
	ret0, _ := ret[0].(*basket.ProductArray)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasket indicates an expected call of GetBasket.
func (mr *MockBasketServiceServerMockRecorder) GetBasket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasket", reflect.TypeOf((*MockBasketServiceServer)(nil).GetBasket), arg0, arg1)
}

// PutInBasket mocks base method.
func (m *MockBasketServiceServer) PutInBasket(arg0 context.Context, arg1 *basket.BasketProduct) (*empty.Empty, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutInBasket", arg0, arg1)
	ret0, _ := ret[0].(*empty.Empty)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutInBasket indicates an expected call of PutInBasket.
func (mr *MockBasketServiceServerMockRecorder) PutInBasket(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutInBasket", reflect.TypeOf((*MockBasketServiceServer)(nil).PutInBasket), arg0, arg1)
}

// mustEmbedUnimplementedBasketServiceServer mocks base method.
func (m *MockBasketServiceServer) mustEmbedUnimplementedBasketServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedBasketServiceServer")
}

// mustEmbedUnimplementedBasketServiceServer indicates an expected call of mustEmbedUnimplementedBasketServiceServer.
func (mr *MockBasketServiceServerMockRecorder) mustEmbedUnimplementedBasketServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedBasketServiceServer", reflect.TypeOf((*MockBasketServiceServer)(nil).mustEmbedUnimplementedBasketServiceServer))
}

// MockUnsafeBasketServiceServer is a mock of UnsafeBasketServiceServer interface.
type MockUnsafeBasketServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeBasketServiceServerMockRecorder
}

// MockUnsafeBasketServiceServerMockRecorder is the mock recorder for MockUnsafeBasketServiceServer.
type MockUnsafeBasketServiceServerMockRecorder struct {
	mock *MockUnsafeBasketServiceServer
}

// NewMockUnsafeBasketServiceServer creates a new mock instance.
func NewMockUnsafeBasketServiceServer(ctrl *gomock.Controller) *MockUnsafeBasketServiceServer {
	mock := &MockUnsafeBasketServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeBasketServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeBasketServiceServer) EXPECT() *MockUnsafeBasketServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedBasketServiceServer mocks base method.
func (m *MockUnsafeBasketServiceServer) mustEmbedUnimplementedBasketServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedBasketServiceServer")
}

// mustEmbedUnimplementedBasketServiceServer indicates an expected call of mustEmbedUnimplementedBasketServiceServer.
func (mr *MockUnsafeBasketServiceServerMockRecorder) mustEmbedUnimplementedBasketServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedBasketServiceServer", reflect.TypeOf((*MockUnsafeBasketServiceServer)(nil).mustEmbedUnimplementedBasketServiceServer))
}
