// Code generated by MockGen. DO NOT EDIT.
// Source: postgre.go

// Package mock_basket is a generated GoMock package.
package mock_basket

import (
	reflect "reflect"

	models "github.com/go-park-mail-ru/2021_2_Good_Vibes/internal/app/models"
	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// DeleteProduct mocks base method.
func (m *MockRepository) DeleteProduct(product models.BasketProduct) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", product)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockRepositoryMockRecorder) DeleteProduct(product interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockRepository)(nil).DeleteProduct), product)
}

// DropBasket mocks base method.
func (m *MockRepository) DropBasket(userId int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DropBasket", userId)
	ret0, _ := ret[0].(error)
	return ret0
}

// DropBasket indicates an expected call of DropBasket.
func (mr *MockRepositoryMockRecorder) DropBasket(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DropBasket", reflect.TypeOf((*MockRepository)(nil).DropBasket), userId)
}

// GetBasket mocks base method.
func (m *MockRepository) GetBasket(userId int) ([]models.BasketProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBasket", userId)
	ret0, _ := ret[0].([]models.BasketProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBasket indicates an expected call of GetBasket.
func (mr *MockRepositoryMockRecorder) GetBasket(userId interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBasket", reflect.TypeOf((*MockRepository)(nil).GetBasket), userId)
}

// PutInBasket mocks base method.
func (m *MockRepository) PutInBasket(basket models.BasketProduct) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutInBasket", basket)
	ret0, _ := ret[0].(error)
	return ret0
}

// PutInBasket indicates an expected call of PutInBasket.
func (mr *MockRepositoryMockRecorder) PutInBasket(basket interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutInBasket", reflect.TypeOf((*MockRepository)(nil).PutInBasket), basket)
}
